package com.xworkz.radio;

import com.xworkz.radio.dao.MusicDAO;
import com.xworkz.radio.dto.MusicDTO;
import com.xworkz.radio.dto.SingerDTO;

public class MusicTester {

	public static void main(String[] args) {
		MusicDTO detailsdto=new MusicDTO();
		detailsdto.setInstrument("Guitar");
		detailsdto.setMusictype("melody");
		detailsdto.setDynamic("softness");
		
		
		SingerDTO dto=new SingerDTO();
		dto.setName("Vijayprakash");
		dto.setNoofsongs((int)95);
		dto.setSalary((long)13000000);
		dto.setGenres("soundtrack");
		detailsdto.setSinger(dto);
		
		MusicDAO dao=new MusicDAO();
		String resp1=dao.insert(detailsdto);
		String resp2=dao.insert(null);
		
		System.out.println(resp1);
		System.out.println(resp2);
		
		dao.printAll();  
	    
		      System.out.println("musictype updated by instrument");
			 MusicDTO musicdetailsdto=dao.updateMusictypeByInstrument("rocking", "venna");
		     System.out.println(musicdetailsdto.toString());
		     
		     System.out.println("dynamic updated by instrument");
		     MusicDTO musicdetailsdto1=dao.updateDynamicByInstrument("roughness", "veena");
		     System.out.println(musicdetailsdto1);
		    
		     
		     System.out.println("data generated by name");
		     MusicDTO details1=dao.getByName("harsha");
		     System.out.println(details1);
		     
		     System.out.println("data generated by salary");
		     MusicDTO details2=dao.getBySalary((long)13537484);
		     System.out.println(details2);
		     
		     
		     
			 System.out.println("data deleted by instrument");  
		     MusicDTO del=dao.deletebyInstrument("guitar");
		     dao.printAll();
				System.out.println(del);	
				 
		     
		     System.out.println("data deleted");  
		     MusicDTO isdelete=dao.deletebyMusictype("melody");
				System.out.println(isdelete);	
				 dao.printAll();
				 
				 
				 

}
}
	

